@client_id=
@client_secret=
@tenant_id=
@marketplace_token=

# @name getToken
POST https://login.microsoftonline.com/{{tenant_id}}/oauth2/token HTTP/1.1
content-type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&grant_type=client_credentials
&resource=20e940b3-4c77-4b0b-9a53-9e16a1b010a7

###

POST https://marketplaceapi.microsoft.com/api/saas/subscriptions/resolve?api-version=2018-08-31 HTTP/1.1
Authorization: Bearer {{getToken.response.body.$.access_token}}
Content-Type: application/json
x-ms-marketplace-token: {{marketplace_token}}
